### ISSUE TITLE
Monitoring des logs

### ISSUE THREAD

**Issue by erwan-haquet** [erwan-haquet/mybicyclejourney#138]
## Description    
Mettre en place un outil de log.

Vérifier que les logs des `Page`s manquantes remontent bien et sont visibles en temps réel

## TODO   
- [x] Installer Sentry
- [x] Revoir l'intégration du `MetadataInjector` pour qu'il ne soit pas trigger à chaque call (profiler, favicon...)
- [x] Exclure les erreurs 404

```
services:
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
```
